variables: variables.yml
tasks:

# Parses imdb id's from imdb.txt and fill Movies list.
  search_imdb:
    disable: builtins
    csv:
      url: file:///{? TempFilePath ?}
      values:
        imdb_id: 1
        url: 0
        title: 0
    accept_all: yes
    list_add:
      - movie_list: New
      - movie_list: Releases

# Removes imdb id's existing in the Releases list from new list.
  find_new_movies:
    disable: builtins
    trakt_list:
      account: '{? TraktAccount ?}'
      list: '$Releases'
      type: movies
    accept_all: yes
    list_remove:
      - movie_list: New

# Add to Trakt Releases lists
  add_trakt_releases:
    disable: builtins
    movie_list: New
    accept_all: yes
    list_add:
      - trakt_list:
          account: '{? TraktAccount ?}'
          list: '$Releases'
          type: movies
      # imdb_list plugin isn't working correctly right now: https://flexget.com/Plugins/List/imdb_list
      #- imdb_list:
      #    login: '{? IMDBAccount ?}'
      #    password: '$Releases'
      #    list: '$Releases'
